Update release.yml
Updated from actions/checkout@v2 to actions/checkout@v3 and 
actions/setup-java@v2 to actions/setup-java@v3.
Updated distribution : 'adopt' to 'temurin'
This is done to resolve following cache error:
Error: getCacheEntry failed: Request timeout: .../_apis/artifactcache/cache?keys=setup-java-Linux-maven-...-setup-java-Linux-maven&version=...